[project]
authors = ["fmac99 <frankmccormick99@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "threat_intel_poc"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.6.0,<25"
python = "3.11.*"

[pypi-dependencies]
networkx = ">=3.4.2, <4"
streamlit = ">=1.42.0, <2"
neo4j = ">=5.28.0, <6"
pandas = "*"
torch = ">=2.6.0, <3"
flask = ">=3.1.0, <4"
matplotlib = ">=3.10.0, <4"
plotly = ">=6.0.0, <7"
jupyter = ">=1.1.1, <2"
groq = ">=0.18.0, <0.19"
sqlalchemy = ">=2.0.38, <3"
